name: Code Quality
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install code quality tools
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 isort
        
    - name: Run Black (formatter check)
      run: black --check --diff .
      
    - name: Run isort (import sorting check)  
      run: isort --check-only --diff .
      
    - name: Run Flake8 (linting)
      run: flake8 .