name: Code Quality
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install code quality tools
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 isort
        
    - name: Run Black (auto-format)
      run: black .
      
    - name: Check if formatting changed files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "❌ Code formatting issues found. Please run 'black .' locally and commit the changes."
          echo ""
          echo "Files that need formatting:"
          git status --porcelain
          echo ""
          echo "Diff of changes:"
          git diff
          exit 1
        else
          echo "✅ Code is properly formatted!"
        fi
        
    - name: Run isort (import sorting check)  
      run: isort --check-only --diff .
      
    - name: Run Flake8 (linting)
      run: flake8 .