name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-docker.txt
        pip install pytest httpx
        
    - name: Run light tests only
      env:
            PYTHONPATH: .  # ← Añadir el directorio actual al PYTHONPATH
      run: |
            pytest tests/test_api_endpoints.py tests/test_validation.py -v